### ISSUE TITLE
BERT LayerNorm doesn't support

### ISSUE THREAD

**Issue by chokchou** [pytorch/opacus#100]
Hello, I want to use opacus on the finetune of the BERT model, but it shows that opacus does not support the LayerNorm module.

```python
class BertLayerNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-12):
        """Construct a layernorm module in the TF style (epsilon inside the square root).
        """
        super(BertLayerNorm, self).__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.bias = nn.Parameter(torch.zeros(hidden_size))
        self.variance_epsilon = eps

    def forward(self, x):
        u = x.mean(-1, keepdim=True)
        s = (x - u).pow(2).mean(-1, keepdim=True)
        x = (x - u) / torch.sqrt(s + self.variance_epsilon)
        return self.weight * x + self.bias
```

May I ask what caused it.And is there any method to solve it?

**Comment by Darktex** [comment]
Hi! The reason you are seeing this is due to the fact that Opacus has one constraint: all of your layers need to be compatible.

A layer if compatible if either of these is true:

- It doesn't have parameters of its own (eg nn.ReLU, or modules that are only containers to other modules)
- If it does have parameters, the module needs to explicitly be whitelisted to be supported. The reason for this is that we need to attach hooks to compute per-sample gradients ad hoc per module.

In your case, I would switch to the "default" `nn.LayerNorm` (yes, that would put the epsilon outside of the sqrt). Another option is to whitelist BertLayerNorm. You can probably do something like this:

```
from opacus.supported_layers_grad_samplers import _supported_layers_grad_samplers, _create_or_extend_grad_sample

def _compute_bert_layer_norm_grad_sample():
    # Copypasta from _compute_norm_grad_sample for nn.LayerNorm
    _create_or_extend_grad_sample(
                layer.weight,
                sum_over_all_but_batch_and_last_n(
                    F.layer_norm(A, layer.normalized_shape, eps=layer.eps) * B,
                    layer.weight.dim(),
                ),
                batch_dim,
            )
    _create_or_extend_grad_sample(
        layer.bias,
        sum_over_all_but_batch_and_last_n(B, layer.bias.dim()),
        batch_dim,
    )


_supported_layers_grad_samplers['BertLayerNorm'] = _compute_bert_layer_norm_grad_sample
```

Note that I haven't tested this, so don't trust that code. Run it by yourself to really check that indeed this works as intended :)

In the future, we plan to make onboarding your own modules much less... err... shitty :P

**Comment by Darktex** [comment]
Also, ICMY we have a tutorial on fine-tuning BERT that doesn't require that step: https://github.com/pytorch/opacus/blob/master/tutorials/building_text_classifier.ipynb

@ffuuugor would know more about how we didn't encounter that issue. It's possible that you might have to update HuggingFace's Transformers?

**Comment by ffuuugor** [comment]
This looks like a custom LayerNorm implementation from transformers==1.0.0 (https://github.com/huggingface/transformers/blob/v1.0.0/pytorch_transformers/modeling_bert.py)

Since then, starting v.2.0, they've switched to using regular `nn.LayerNorm` which we do support.

The easiest workaround, would be, of course, to update to a newer `transformers` version

**Comment by ilyamironov** [comment]
@chokchou, does @ffuuugor's answer resolve your issue?

**Comment by chokchou** [comment]
@ilyamironov ,I encountered an error during fellow Darktex's method:
NameError: name 'sum_over_all_but_batch_and_last_n' is not defined.
So I replaced the BertLayerNorm module with nn.LayerNorm，and solved the problem. 
Thank you all.
