### ISSUE TITLE
Attached optimizer should not touch parameters that weren't passed to it

### ISSUE THREAD

**Issue by ndrmnl** [pytorch/opacus#225]
## 🐛 Bug

The `step` done by the `PrivacyEngine` considers all the parameters that have `requires_grad = True`, whether or not they have been passed to the attached optimizer.

An easy fix is to go through `optimizer.param_groups` rather than through the `self.module.parameters` in L501 of the `PrivacyEngine`.

## To Reproduce

A `step` on the `dp_optimizer` below will also update layer 1.

```
model = torch.nn.Sequential(torch.nn.Linear(5, 10), torch.nn.Linear(10, 1))

dp_params = [p[1] for p in model.named_parameters() if p[0].startswith('0')]
dp_optimizer = torch.optim.SGD(dp_params, lr=0.01)
privacy_engine.attach(dp_optimizer)
```

## Expected behavior

The optimizer shouldn't touch parameters that were not passed to it.

**Comment by ffuuugor** [comment]
Hi @ndrmnl, and thanks for pointing out the issue - the expected behaviour you described is indeed what should happen.

We're currently actively working on a new release of Opacus with a major revamp of the API to simplify the code (see branch `experimental_v1.0`). The issue described here is already fixed in the new version and will be available once we ship the changes (plan is mid-November). 

As for the short-term, I don't think we'll be able to prioritise that - the long-term fix is coming relatively soon, and I don't think this is going to be a one-line change (in addition to L501 you'd also need to adjust the clipping and how you calculate sample grad norm)

Thanks again for opening this issue. Let's leave it open and close it once we land the changes and verify they resolve the problem
