### ISSUE TITLE
BatchSplittingSampler generates numpy.int64 split indices

### ISSUE THREAD

**Issue by gugarosa** [pytorch/opacus#406]
## 🐛 Bug

Hello! Hope everyone is doing well!

Is there any particular reason why the `__iter__()` function of `BatchSplittingSampler` generates split indices (`split_idxs`) as `numpy.int64`?
https://github.com/pytorch/opacus/blob/main/opacus/utils/batch_memory_manager.py#L56

Such behavior might break with pre-defined datasets that not support such typing for indexing. For example, the `huggingface/datasets` package has a check that inhibits from using numpy-based types.
https://github.com/huggingface/datasets/blob/master/src/datasets/formatting/formatting.py#L40

Should the items from `split_idxs` be replaced by Python native `int` for better compatibility?

I am doing a naïve workaround by just adding `split_idxs = [s.tolist() for s in split_idxs]`, but it feels somewhat overwhelming to abstract a class just for adding one line.

Best regards,
Gustavo.

**Comment by karthikprasad** [comment]
Hi @gugarosa,
Thanks for flagging this and for calling out the failure case wrt huggingface. 

> Is there any particular reason why the __iter__() function of BatchSplittingSampler generates split indices (split_idxs) as numpy.int64?

Nothing intentional AFAIK; this is just a consequence of `np.array_split()`, which just happens to change the dtype to `np.int64` ¯\_(ツ)_/¯ 

> but it feels somewhat overwhelming to abstract a class just for adding one line.

Completely agree. Perhaps we can include your workaround in the main code after https://github.com/pytorch/opacus/blob/main/opacus/utils/batch_memory_manager.py#L58. Would you like to send out a PR?

**Comment by gugarosa** [comment]
Thanks @karthikprasad for your response!

Sounds great! I will check beforehand if there is a smarter way to return the `int` dtype instead of using an extra list comprehension and definitely send the PR.

Thanks so much and best regards,
Gustavo.
